---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'Alertmanager'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'speedtest'
    metrics_path: /metrics
    scrape_interval: 30m
    scrape_timeout: 60s  # running speedtest needs time to complete
    static_configs:
      - targets: ['192.168.0.150:9798']

  - job_name: 'ping'
    metrics_path: /probe
    scrape_interval: 5s
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
          - pinghosts.yaml
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*);(.*)'  # first is the url, thus unique for instance
        target_label: instance
        replacement: $1
      - source_labels: [__address__]
        regex: '(.*);(.*)'  # second is humanname to use in charts
        target_label: humanname
        replacement: $2
      - source_labels: [instance]
        target_label: __param_target
      - target_label: __address__
        replacement: ping:9115  # The blackbox exporter's real hostname:port.

#  - job_name: 'nodeexp'
#    static_configs:
#      - targets: ['nodeexp:9100']
  - job_name: 'traefik'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.150:8081']
  - job_name: 'pihole'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.150:9617']

  - job_name: 'snmp'
    static_configs:
      - targets:
        - 192.168.0.2  # SNMP device.
        - 192.168.0.3  # SNMP device.
    metrics_path: /snmp
    params:
      auth: [public_v2]
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mk_snmp_exporter:9116 
  - job_name: 'nodeexp-pfsense'
    static_configs:
      - targets: ['192.168.0.1:9100']