version: '3'
services:
  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    security_opt:
    - no-new-privileges:false
    networks:
    - proxy
    volumes:
    - /etc/localtime:/etc/localtime
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/user/tautulli/config:/config
    environment:
    - PUID=1000
    - PGID=100
    - TZ=Australia/Sydney
    labels:
    - traefik.enable=true
    - traefik.http.routers.tautulli.entrypoints=http
    - traefik.http.routers.tautulli.rule=Host(`tautulli.local.example.com`)
    - traefik.http.middlewares.tautulli-https-redirect.redirectscheme.scheme=https
    - traefik.http.routers.tautulli.middlewares=tautulli-https-redirect
    - traefik.http.routers.tautulli-secure.entrypoints=https
    - traefik.http.routers.tautulli-secure.rule=Host(`tautulli.local.example.com`)
    - traefik.http.routers.tautulli-secure.tls=true
    - traefik.http.routers.tautulli-secure.service=tautulli
    - traefik.http.services.tautulli.loadbalancer.server.port=8181
    - traefik.docker.network=proxy
networks:
  proxy:
    external: true
