version: '3'
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    security_opt:
    - no-new-privileges:false
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Australia/Sydney
    - WEBUI_PORT=8080
    networks:
    - proxy
    volumes:
    - /etc/localtime:/etc/localtime
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/user/qbittorrent/config:/config
    - /mnt/nasMedia:/downloads
    ports:
    - 6881:6881
    - 6881:6881/udp
    labels:
    - traefik.enable=true
    - traefik.http.routers.qbittorrent.entrypoints=http
    - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.local.example.com`)
    - traefik.http.middlewares.qbittorrent-https-redirect.redirectscheme.scheme=https
    - traefik.http.routers.qbittorrent.middlewares=qbittorrent-https-redirect
    - traefik.http.routers.qbittorrent-secure.entrypoints=https
    - traefik.http.routers.qbittorrent-secure.rule=Host(`qbittorrent.local.example.com`)
    - traefik.http.routers.qbittorrent-secure.tls=true
    - traefik.http.routers.qbittorrent-secure.service=qbittorrent
    - traefik.http.services.qbittorrent.loadbalancer.server.port=8080
    - traefik.docker.network=proxy
networks:
  proxy:
    external: true
