version: '3'
services:
  speedtracker:
    image: henrywhitaker3/speedtest-tracker
    container_name: speedtracker
    restart: unless-stopped
    security_opt:
    - no-new-privileges:false
    networks:
    - proxy
    volumes:
    - /etc/localtime:/etc/localtime
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/user/speedtracker/config:/config
    environment:
    - TZ=Australia/Sydney
    - PGID=1000
    - PUID=1000
    - OOKLA_EULA_GDPR=true
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 200k
    labels:
    - traefik.enable=true
    - traefik.http.routers.speedtracker.entrypoints=http
    - traefik.http.routers.speedtracker.rule=Host(`speedtracker.local.example.com`)
    - traefik.http.middlewares.speedtracker-https-redirect.redirectscheme.scheme=https
    - traefik.http.routers.speedtracker.middlewares=speedtracker-https-redirect
    - traefik.http.routers.speedtracker-secure.entrypoints=https
    - traefik.http.routers.speedtracker-secure.rule=Host(`speedtracker.local.example.com`)
    - traefik.http.routers.speedtracker-secure.tls=true
    - traefik.http.routers.speedtracker-secure.service=speedtracker
    - traefik.http.services.speedtracker.loadbalancer.server.port=80
    - traefik.docker.network=proxy
networks:
  proxy:
    external: true
