version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser:latest
    container_name: file-browser
    user: 1000:1000
    networks:
    - proxy
    volumes:
    - /home/user/:/srv
    - /home/user/filebrowser/filebrowser.db:/database.db
    restart: unless-stopped
    labels:
    - traefik.enable=true
    - traefik.http.routers.filebrowser.entrypoints=http
    - traefik.http.routers.filebrowser.rule=Host(`filebrowser.local.example.com`)
    - traefik.http.middlewares.filebrowser-https-redirect.redirectscheme.scheme=https
    - traefik.http.routers.filebrowser.middlewares=filebrowser-https-redirect
    - traefik.http.routers.filebrowser-secure.entrypoints=https
    - traefik.http.routers.filebrowser-secure.rule=Host(`filebrowser.local.example.com`)
    - traefik.http.routers.filebrowser-secure.tls=true
    - traefik.http.routers.filebrowser-secure.service=filebrowser
    - traefik.http.services.filebrowser.loadbalancer.server.port=80
    - traefik.docker.network=proxy
networks:
  proxy:
    external: true
