version: '3'
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Australia/Sydney
    - SUDO_PASSWORD=password
    security_opt:
    - no-new-privileges:false
    volumes:
    - /home/user/vscode/config:/config
    - /etc/localtime:/etc/localtime
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - proxy
    restart: unless-stopped
    labels:
    - traefik.enable=true
    - traefik.http.routers.vscode.entrypoints=http
    - traefik.http.routers.vscode.rule=Host(`vscode.local.example.com`)
    - traefik.http.middlewares.vscode-https-redirect.redirectscheme.scheme=https
    - traefik.http.routers.vscode.middlewares=vscode-https-redirect
    - traefik.http.routers.vscode-secure.entrypoints=https
    - traefik.http.routers.vscode-secure.rule=Host(`vscode.local.example.com`)
    - traefik.http.routers.vscode-secure.tls=true
    - traefik.http.routers.vscode-secure.service=vscode
    - traefik.http.services.vscode.loadbalancer.server.port=8443
    - traefik.docker.network=proxy
networks:
  proxy:
    external: true
